name: 'Terraform container actions'
description: 'Terraform action demonstrates via a Secure OIDC'
author: 'KhaiWah'
inputs:
  TF_STAGE:
    description: ''
    required: true
    default: 'plan'
  STATE_KEY:
    description: ''
    required: true
  DJANGO_SECRET_KEY_PROD:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
